<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-25 at 12:28:08.
 */
class snatsortTest extends PHPUnit_Framework_TestCase {

	/**
	 * @covers sasort
	 * @group  stablesort
	 */
	public function testAssociation() {
		$array = array('a9', 'a1', 'a10', 'A2');
		snatsort($array);
		$this->assertSame(array(3 => 'A2', 1 => 'a1', 0 => 'a9', 2 => 'a10'), $array);
	}
}
