<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-25 at 12:28:08.
 */
class suksortTest extends PHPUnit_Framework_TestCase {

	public function compare_string_skip($a, $b) {
		return strcmp(substr($a, 1), substr($b, 1));
	}
		
	/**
	 * @covers sasort
	 * @group  stablesort
	 */
	public function testAssociation() {
		$source = array(
			'a3'	=> 1,
			'b2'	=> 2,
			'c2'	=> 3,
			'd1'	=> 4,
		);
		
		$expected = array(
			'd1'	=> 4,
			'b2'	=> 2,
			'c2'	=> 3,
			'a3'	=> 1,
		);
		
		
		$array = $source;
		uksort($array, array($this, 'compare_string_skip'));
		$this->assertNotSame($expected, $array);
		
		$array = $source;
		suksort($array, array($this, 'compare_string_skip'));
		$this->assertSame($expected, $array);
	}
}
